### ISSUE TITLE
After selecting all for input system for contributors, deselecting one language still shows the language

### ISSUE THREAD

**Issue by yejoo24** [sil-student-projects/2018-web-languageforge-config#91]
-Create user and set user as contributors
-Select all under contributors on input systems
-deselect a language and apply
-Go log in as the said new user and the language is still there, despite being deselcted

**Comment by irahopkinson** [comment]
Fixed in https://github.com/sillsdev/web-languageforge/commit/888a64dec505c7a04d8e9790150c9102bdcb78d9
