### ISSUE TITLE
Somehow the settings for manager is being applied to contributors

### ISSUE THREAD

**Issue by yejoo24** [sil-student-projects/2018-web-languageforge-config#99]
-Select things for manager 
-See the things selected or deselected for manager appear for contributors. (for example, when i ticked off espanol for manager after selecting all for manager, the espanol does not show up contributors. making all the manager blank results in a blank dictionary (which is expected for managers only) for contributors.

**Comment by irahopkinson** [comment]
Fixed in https://github.com/sillsdev/web-languageforge/commit/888a64dec505c7a04d8e9790150c9102bdcb78d9
